# Generated by Django 6.0.6 on 2026-07-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='blank'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(null=True, upload_to='posts/'),
        ),
    ]
